{% set name = "google-cloud-pubsub" %}
{% set version = "1.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cdb133910f04fa2151c9b96aed1403fc968e32d146e39e7b03735127a9138c63

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - google-api-core
    - grpc-google-iam-v1
    - enum34

test:
  imports:
    - google.cloud.pubsub_v1

about:
  home: https://github.com/googleapis/google-cloud-python/tree/master/pubsub
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python Client for Google Cloud Pub / Sub

  # The remaining entries in this section are optional, but recommended.
  description: |
    Google Cloud Pub / Sub is a fully-managed real-time messaging service that
    allows you to send and receive messages between independent applications.
    You can leverage Cloud Pub/Sub’s flexibility to decouple systems and
    components hosted on Google Cloud Platform or elsewhere on the Internet. By
    building on the same technology Google uses, Cloud Pub / Sub is designed to
    provide “at least once” delivery at low latency with on-demand scalability
    to 1 million messages per second (and beyond).


extra:
  recipe-maintainers:
    - hmaarrfk
