{% set name = "google-cloud-pubsub" %}
{% set version = "2.27.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7119dbc5af4b915ecdfa1289919f791a432927eaaa7bbfbeb740e6d7020c181e

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    # expressing the google-api-core-grpc dependency this way enables grayskull bot
    # autodetection of version updates from upstream library
    - google-api-core >=1.34.0,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,!=2.10.*
    - google-api-core-grpc
    - google-auth >=2.14.1,<3.0.0dev
    - grpc-google-iam-v1 >=0.12.4,<1.0.0dev
    - grpcio >=1.51.3,<2.0dev
    - grpcio-status >=1.33.2
    - opentelemetry-api >=1.27.0
    - opentelemetry-sdk >=1.27.0
    # use tighter constraint for python >=3.13 to stay noarch: python
    - proto-plus >=1.25.0,<2.0.0dev
    - protobuf >=3.20.2,<6.0.0dev,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5
    # from libcst extra
    - libcst >=0.3.10

test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
  imports:
    - google.api_core
    - google.cloud.pubsub
    - grpc

about:
  home: https://pypi.org/project/google-cloud-pubsub/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python Client for Google Cloud Pub / Sub
  dev_url: https://github.com/googleapis/python-pubsub
  doc_url: https://cloud.google.com/python/docs/reference/pubsub/latest
  description: |
    Google Cloud Pub / Sub is a fully-managed real-time messaging service that
    allows you to send and receive messages between independent applications.
    You can leverage Cloud Pub/Sub’s flexibility to decouple systems and
    components hosted on Google Cloud Platform or elsewhere on the Internet. By
    building on the same technology Google uses, Cloud Pub / Sub is designed to
    provide “at least once” delivery at low latency with on-demand scalability
    to 1 million messages per second (and beyond).


extra:
  recipe-maintainers:
    - xylar
    - hmaarrfk
    - tpdownes
    - tswast
